### ISSUE TITLE
NixOS experience is discouraging

### ISSUE THREAD

**Issue by bugeats** [bravit/hid-examples#11]
Hey I'm just starting the book and getting my dev environment setup. I use NixOS even though I don't understand it very well and I probably have no business making demands about accommodating it. I just wanted to let you know that my experience so far has been discouraging:

    $ stack build
    error: attribute 'ghc8104' missing, at (string):1:43

Ok so I either need to figure out the nix-fu to get that older resolver installed, or I need to update `stack.yml` to use my system GHC. I went for the later. 

```yaml
# stack.yaml

resolver:
  compiler: ghc-8.10.7

nix:
  enable: true

...
```

Ok, try again:

    $ stack build

    Error: While constructing the build plan, the following exceptions were encountered:

    In the dependencies for Chart-diagrams-1.9.3:
        Chart must match >=1.9 && <1.10, but the stack configuration has no specified version  (latest matching version is 1.9.3)
        blaze-markup must match >=0.7 && <0.9, but the stack configuration has no specified version  (latest matching version is 0.8.2.8)
        colour must match >=2.2.1 && <2.4, but the stack configuration has no specified version  (latest matching version is 2.3.6)
        data-default-class must match <0.2, but the stack configuration has no specified version  (latest matching version is 0.1.2.0)
        lens must match >=3.9 && <5.1, but the stack configuration has no specified version  (latest matching version is 5.0.1)
        old-locale needed, but the stack configuration has no specified version  (latest matching version is 1.0.0.7)
        operational must match >=0.2.2 && <0.3, but the stack configuration has no specified version  (latest matching version is 0.2.4.1)
    needed due to hid-examples-0.5 -> Chart-diagrams-1.9.3

    < ... and a bunch of other redacted dependency issues ... >

----

My understanding is that stack has first-class support for nix, so I was hoping this would all just work out of the box. It seems that I could write some custom config for `nix-shell` to ensure the correct environment, but that's beyond my abilities at this point.

**Comment by juhp** [comment]
You don't want to use a ghc resolver: that only gives you the libraries included with ghc.

**Comment by kczulko** [comment]
@bugeats 

With the latest nixos version (22.05) I also stopped compiling for me (I am using cabal). It has quite recent cabal and ghc:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2
$ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library
```

However, creating nix-shell with cabal and ghc8107 (just following [this](https://github.com/bravit/hid-examples/issues/15#issuecomment-1050039409) advice) fixed my problem. So this works in my case:
```nix
pkgs.mkShell {
  buildInputs = [
    pkgs.haskell.packages.ghc8107.cabal-install
    pkgs.haskell.packages.ghc8107.ghc
    ...
  ]
```

**Comment by kayvank** [comment]
also, you might consider using the [hs-nix-template](https://github.com/utdemir/hs-nix-template) . It is reliable and documented well, easy to use.
