### ISSUE TITLE
'cabal build' fails with cabal 3.12.1

### ISSUE THREAD

**Issue by anguwardavi** [bravit/hid-examples#20]
I cloned the latest hid-examples as of Oct31,2024 but when I run 'cabal build', I get this:
$ cabal --version
cabal-install version 3.12.1.0
compiled using version 3.12.1.0 of the Cabal library 

$ cabal build
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: hid-examples-0.5 (user goal)
[__1] trying: req-3.13.4 (dependency of hid-examples)
[__2] trying: modern-uri-0.3.6.1 (dependency of req)
[__3] trying: megaparsec-9.6.1 (dependency of modern-uri)
[__4] trying: scientific-0.3.8.0 (dependency of megaparsec)
[__5] trying: binary-0.8.9.2/installed-ab44 (dependency of scientific)
[__6] trying: colonnade-1.2.0.2 (dependency of hid-examples)
[__7] trying: Chart-diagrams-1.9.5.1 (dependency of hid-examples)
[__8] next goal: text (dependency of hid-examples)
[__8] rejecting: text-2.1.1/installed-05f2 (conflict: colonnade => text>=1.0 && <2.1)
[__8] skipping: text; 2.1.2, 2.1.1, 2.1 (has the same characteristics that caused the previous version to fail: excluded by constraint '>=1.0 && <2.1' from 'colonnade')
[__8] trying: text-2.0.2
[__9] trying: lens-5.3.2 (dependency of hid-examples)
[_10] next goal: containers (dependency of hid-examples)
[_10] rejecting: containers-0.7/installed-622f (conflict: text => deepseq>=1.1 && <1.5, containers => deepseq==1.5.0.0/installed-c88a)
[_10] rejecting: containers; 0.7, 0.6.8, 0.6.7, 0.6.6, 0.6.5.1, 0.6.4.1, 0.6.3.1, 0.6.2.1, 0.6.1.1, 0.6.0.1, 0.5.11.0, 0.5.10.2, 0.5.10.1, 0.5.9.2, 0.5.8.2, 0.5.7.1, 0.5.7.0, 0.5.6.3, 0.5.6.2, 0.5.6.1, 0.5.6.0, 0.5.5.1, 0.5.5.0, 0.5.4.0, 0.5.3.1, 0.5.3.0, 0.5.2.1, 0.5.2.0, 0.5.1.0, 0.5.0.0, 0.4.2.1, 0.4.2.0, 0.4.1.0, 0.4.0.0, 0.3.0.0, 0.2.0.1, 0.2.0.0, 0.1.0.1, 0.1.0.0, 0.5.9.1, 0.5.8.1 (conflict: binary => containers==0.7/installed-622f)
[_10] fail (backjumping, conflict set: binary, containers, hid-examples, text)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: lens, hid-examples, template-haskell, text, Chart-diagrams, containers, binary, colonnade, scientific, base, megaparsec, modern-uri, req
Try running with --minimize-conflict-set to improve the error message.

**Comment by bravit** [comment]
Hi @anguwardavi! It seems you're using GHC 9.10. Unfortunately, it's not supported. There are some dependencies that are not yet updated to support GHC 9.10. At this time, I recommend trying with GHC 9.8 or using `stack` for building the project.

**Comment by bravit** [comment]
Closing this now as it seems that `cabal` builds the project now (given that the list of packages is updated).
