### ISSUE TITLE
`stack build` command failed with the message can't load framework: Cocoa (not found)

### ISSUE THREAD

**Issue by jtonic** [bravit/hid-examples#7]
`stack build` command failed with the following message: 

diagrams-lib       > <command line>: can't load framework: Cocoa (not found)

I believe this has to do with the new macos version big sur.

I've read something about it here. https://gitlab.haskell.org/ghc/ghc/-/issues/18592 

I've tried locally to update the `resolver` (stack.yml) from `lts-14.27` to newer ones (i.e: resolver: lts-16.31) but I started to stumble upon some issues with dependencies' versions.
I really like the book but I would like to run the examples on my machine. I am really interested in learning to develop production with haskell and this book looks like a good fit for my adventure.

Is there something I can do on my side?

Thanks

Info:

❯ stack exec -- which ghc
     /Users/xxx/.stack/programs/x86_64-osx/ghc-8.6.5/bin/ghc
System Version:	macOS 11.2.1 (20D74)
Kernel Version:	Darwin 20.3.0

**Comment by bravit** [comment]
Hi Antonel, thanks for opening this issue! I've updated the `stack.yaml` file. Could you please check if the current version works for you?

**Comment by jtonic** [comment]
Hi @bravit 

It is fine now. `stack build` and `stack test` commands run without any issue.
The only thing that could improve (at least) my experience of working with haskell, would be to use another stackage, in order to have support for the vs code haskell language server.

I know that IDEs is totally another story, but, at least for me, having a decent support in the IDE (vs code) would be a tremendous good addition to the development toolbox.

In one of my learning projects I switched from `LTS Haskell 17.4 (ghc-8.10.4)` to `LTS Haskell 16.31 (ghc-8.8.4)` just to have this support.

You can see here the ghc versions currently supported by the VS code haskell extension.

https://github.com/haskell/vscode-haskell#supported-ghc-versions 

Is it possible to have the stackage `LTS Haskell 16.31 (ghc-8.8.4)` instead of the current one (even if in a different branch)? Just if you consider this worth the effort.


Thank you. 

Note:
- This is the exception I've got with the VS code Haskell extension using the GHC version brought by the current stackage.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/513581/108355295-4d220980-71f3-11eb-9b63-66b94f89b742.png">

**Comment by bravit** [comment]
Unfortunately, there is a problem. The bug you've encountered while using Big Sur is the bug in GHC. It was fixed in `ghc-9.0.1` and then backported to `ghc-8.8.5` and `ghc-8.10.3`. You could try `resolver: lts-17.2` in `stack.yaml` and see if it works for your setup.

**Comment by jtonic** [comment]
I will try your suggestion.
Definitely the initial reported issue has been fixed.
You can close it. 

Thanks again for your help.

**Comment by jtonic** [comment]
Your suggestion works, and the Haskell language server has been successfully downloaded and install by vs code.

This is great. Thanks.

There is nothing stopping me now to start learning Haskell, considering that I also have an amazing companion: Haskell in depth book. ;)
