### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ted-kord** [bravit/hid-examples#9]
When I do `cabal build`, I get:

> [tedkord@fedora hid-examples]$ cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: hid-examples-0.5 (user goal)
[__1] rejecting: hid-examples:!test (constraint from config file, command line
flag, or user target requires opposite flag selection)
[__1] trying: hid-examples:*test
[__2] trying: doctest-0.18.1 (dependency of hid-examples *test)
[__3] trying: ghc-8.8.4/installed-8.8... (dependency of doctest)
[__4] trying: req-3.9.1 (dependency of hid-examples)
[__5] trying: transformers-base-0.4.6 (dependency of req)
[__6] trying: transformers-compat-0.7 (dependency of transformers-base)
[__7] trying: http-client-tls-0.3.5.3 (dependency of req)
[__8] trying: network-uri-2.6.4.1 (dependency of http-client-tls)
[__9] trying: parsec-3.1.14.0/installed-3.1... (dependency of network-uri)
[_10] trying: Chart-diagrams-1.9.3 (dependency of hid-examples)
[_11] trying: diagrams-postscript-1.5 (dependency of Chart-diagrams)
[_12] next goal: statestack (dependency of diagrams-postscript)
[_12] rejecting: statestack-0.3, statestack-0.2.0.5 (conflict:
transformers-compat==0.7, statestack => transformers-compat>=0.4 && <0.7)
[_12] rejecting: statestack-0.2.0.4, statestack-0.2.0.3 (conflict: ghc =>
transformers==0.5.6.2/installed-0.5..., statestack => transformers>=0.3 &&
<0.5)
[_12] rejecting: statestack-0.2 (conflict: parsec =>
mtl==2.2.2/installed-2.2..., statestack => mtl>=2.1 && <2.2)
[_12] rejecting: statestack-0.1.1, statestack-0.1 (conflict:
diagrams-postscript => statestack>=0.2 && <0.4)
[_12] fail (backjumping, conflict set: diagrams-postscript, ghc, parsec,
statestack, transformers-compat)
Backjump limit reached (currently 4000, change with --max-backjumps or try to
run with --reorder-goals).

With `stack build`, these lines and others similar make the build fail:

> Only                             > <no location info>: error:
Only                             >     Warning: Couldn't figure out linker information!
Only                             >              Make sure you're using GNU ld, GNU gold or the built in OS X linker, etc.
Only                             > collect2: fatal error: cannot find ‘ld’
Only                             > compilation terminated.
Only                             > `gcc' failed in phase `Linker'. (Exit code: 1)

My stack version is:
`Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4`

and my cabal version is:
`cabal-install version 3.0.0.0
compiled using version 3.0.1.0 of the Cabal library`

**Comment by timjstewart** [comment]
I have the same problem.  I worked around it by using `stack` to build the system as shown on page xxx.
